stages:
  - test
  - build
  - release

eslint:
  image: node:6
  stage: test
  tags:
    - docker
  script:
    - npm install --quiet
    - npm run lint

android:
  image: elviejokike/react-native-android
  stage: build
  artifacts:
    paths:
      - android/app/build/outputs/apk/app-release.apk
      - android/sourcemap.js
    expire_in: '1 mos'
  script:
    - npm install --quiet
    - npm run postinstall
    - cd android
    - ./buildGitlabRunner.sh
  only:
    - tags
    - master
    - /^v\d+\.\d+.*$/ # Version branches
  tags:
    - android

ios:
  stage: build
  tags:
    - osx
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - ios/main.jsbundle.map
      - TelldusLiveApp.ipa
      - TelldusLiveApp.app.dSYM.zip
    expire_in: '1 mos'
  only:
    - tags
    - master
    - /^v\d+\.\d+.*$/ # Version branches
  script:
    - npm install --quiet
    - cd ios
    - ./buildGitlabRunner.sh

google_play:
  image: ruby:2
  stage: release
  tags:
    - docker
  dependencies:
    - android
  environment:
    name: production
    url: https://play.google.com/store/apps/details?id=com.telldus.live.mobile.test
  when: manual
  only:
    - tags
  script:
    - echo ${GOOGLE_KEY} > play_key.json
    - bundle install
    - fastlane supply --apk android/app/build/outputs/apk/app-release.apk --track alpha

testflight:
  stage: release
  tags:
    - osx
  dependencies:
    - ios
  environment:
    name: production
    url: https://itunes.apple.com/us/app/telldus-live-mobile-beta/id1014419677
  when: manual
  only:
    - tags
  script:
    - fastlane ios build
